# Generated by Django 3.2.5 on 2024-05-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('DEVICEID', models.CharField(max_length=255)),
                ('NAME', models.CharField(blank=True, max_length=255, null=True)),
                ('WORKGROUP', models.CharField(blank=True, max_length=255, null=True)),
                ('USERDOMAIN', models.CharField(blank=True, max_length=255, null=True)),
                ('OSNAME', models.CharField(blank=True, max_length=255, null=True)),
                ('OSVERSION', models.CharField(blank=True, max_length=255, null=True)),
                ('OSCOMMENTS', models.CharField(blank=True, max_length=255, null=True)),
                ('PROCESSORT', models.CharField(blank=True, max_length=255, null=True)),
                ('PROCESSORS', models.IntegerField(default=0)),
                ('PROCESSORN', models.SmallIntegerField(blank=True, null=True)),
                ('MEMORY', models.IntegerField(blank=True, null=True)),
                ('SWAP', models.IntegerField(blank=True, null=True)),
                ('IPADDR', models.CharField(blank=True, max_length=255, null=True)),
                ('DNS', models.CharField(blank=True, max_length=255, null=True)),
                ('DEFAULTGATEWAY', models.CharField(blank=True, max_length=255, null=True)),
                ('ETIME', models.DateTimeField(blank=True, null=True)),
                ('LASTDATE', models.DateTimeField(blank=True, null=True)),
                ('LASTCOME', models.DateTimeField(blank=True, null=True)),
                ('QUALITY', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('FIDELITY', models.BigIntegerField(default=1)),
                ('USERID', models.CharField(blank=True, max_length=255, null=True)),
                ('TYPE', models.IntegerField(blank=True, null=True)),
                ('DESCRIPTION', models.CharField(blank=True, max_length=255, null=True)),
                ('WINCOMPANY', models.CharField(blank=True, max_length=255, null=True)),
                ('WINOWNER', models.CharField(blank=True, max_length=255, null=True)),
                ('WINPRODID', models.CharField(blank=True, max_length=255, null=True)),
                ('WINPRODKEY', models.CharField(blank=True, max_length=255, null=True)),
                ('USERAGENT', models.CharField(blank=True, max_length=50, null=True)),
                ('CHECKSUM', models.BigIntegerField(default=262143)),
                ('SSTATE', models.IntegerField(default=0)),
                ('IPSRC', models.CharField(blank=True, max_length=255, null=True)),
                ('UUID', models.CharField(blank=True, max_length=255, null=True)),
                ('ARCH', models.CharField(blank=True, max_length=10, null=True)),
                ('CATEGORY_ID', models.IntegerField(blank=True, null=True)),
                ('ARCHIVE', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hardware',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='sima_equipos',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('SSN', models.CharField(blank=True, max_length=255, null=True)),
                ('Nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('SO', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('MACADDR', models.CharField(blank=True, max_length=255, null=True)),
                ('IPADDRESS', models.CharField(blank=True, max_length=255, null=True)),
                ('Semaforo', models.CharField(blank=True, max_length=255, null=True)),
                ('inventario', models.CharField(blank=True, max_length=255, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('smodel', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Equipos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vista_Equipos',
            fields=[
                ('SSN', models.CharField(blank=True, max_length=255, null=True)),
                ('smanufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('smodel', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('bversion', models.CharField(blank=True, max_length=255, null=True)),
                ('bdate', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Equipo', models.CharField(blank=True, max_length=255, null=True)),
                ('SO', models.CharField(blank=True, max_length=255, null=True)),
                ('Osversion', models.CharField(blank=True, max_length=255, null=True)),
                ('PROCESSORT', models.CharField(blank=True, max_length=255, null=True)),
                ('RAM', models.CharField(blank=True, max_length=255, null=True)),
                ('ARCH', models.CharField(blank=True, max_length=255, null=True)),
                ('MON_MANUFACTURER', models.CharField(blank=True, max_length=255, null=True)),
                ('MON_CAPTION', models.CharField(blank=True, max_length=255, null=True)),
                ('MON_SERIAL', models.CharField(blank=True, max_length=255, null=True)),
                ('VID_NAME', models.CharField(blank=True, max_length=255, null=True)),
                ('VID_MEMORY', models.CharField(blank=True, max_length=255, null=True)),
                ('MACADDR', models.CharField(blank=True, max_length=255, null=True)),
                ('IPADDRESS', models.CharField(blank=True, max_length=255, null=True)),
                ('Tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('Semaforo', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Vista_Equipos',
                'managed': False,
            },
        ),
    ]
